apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -v convert -f docker-compose.yml -o export
    kompose.version: 1.16.0 (0c01309)
    traefik.enable: "true"
    traefik.http.middlewares.redirect.redirectscheme.scheme: https
    traefik.http.routers.cells-secure.entrypoints: websecure
    traefik.http.routers.cells-secure.rule: Host(`pydio.pfechercheriattia.fr`)
    traefik.http.routers.cells-secure.service: cells
    traefik.http.routers.cells-secure.tls: "true"
    traefik.http.routers.cells-secure.tls.certresolver: mydnschallenge
    traefik.http.routers.cells.entrypoints: dashboard
    traefik.http.routers.cells.middlewares: redirect
    traefik.http.routers.cells.rule: Host(`pydio.pfechercheriattia.fr`)
    traefik.http.services.cells.loadbalancer.server.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: cells-malek
  name: cells-malek
  namespace: traefik
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 80
  selector:
    io.kompose.service: cells-malek
status:
  loadBalancer: {}
