apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -v convert -f docker-compose.yml -o export
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
