version: "3"

services:
  traefik:
    image: ldez/traefik:ns1
    ports:
      - 80:80
    environment:
      CLOUDFLARE_EMAIL: 'malek.attia@telecom-sudparis.eu'
      CLOUDFLARE_API_KEY: 'f58f96f264470b712c995832654f06827c876'
    volumes:
      - ./docker/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:pfechercheriattia.fr"
