apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  containers:
  - name: pdfmagic
    image: attiamalek/proxy:latest
    resources:
      requests:
        cpu: 0.5
    ports:
    - containerPort: 8080
