apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cells-pv-claim
  namespace: traefik
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
