apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: traefik
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/outscale/projet/data"
