apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
    traefik.enable: "true"
    traefik.http.middlewares.cells-https-redirect.redirectscheme.scheme: https
    traefik.http.routers.cells-secure.entrypoints: websecure
    traefik.http.routers.cells-secure.rule: Host(`pydio.pfechercheriattia.fr`)
    traefik.http.routers.cells-secure.service: cells
    traefik.http.routers.cells-secure.tls: "true"
    traefik.http.routers.cells-secure.tls.certresolver: mydnschallenge
    traefik.http.routers.cells.entrypoints: dashboard
    traefik.http.routers.cells.middlewares: cells-https-redirect
    traefik.http.routers.cells.rule: Host(`pydio.pfechercheriattia.fr`)
    traefik.http.services.cells.loadbalancer.server.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: cells
  name: cells
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cells
    spec:
      containers:
      - env:
        - name: CELLS_BIND
          value: https://0.0.0.0:80
        - name: CELLS_EXTERNAL
          value: https://pydio.pfechercheriattia.fr
        - name: CELLS_NO_TLS
          value: "1"
        image: attiamalek/cells:firsttry
        name: cells
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
