apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
    traefik.http.routers.api.entrypoints: dashboard
    traefik.http.routers.api.rule: Host(`pfechercheriattia.fr`)  && (PathPrefix(`/api`)
      || PathPrefix(`/dashboard`))
    traefik.http.routers.api.service: api@internal
  creationTimestamp: null
  labels:
    io.kompose.service: reverse
  name: reverse
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: reverse
status:
  loadBalancer: {}
